import Foundation

extension Word {
    static let hard: [Word] = [
        Word(word: "Abstruse", pronunciation: "ab-STRUSE",
             definition: "Difficult to understand",
             sentence: "The theory was abstruse for most students.",
             difficulty: .hard),
        Word(word: "Acumen", pronunciation: "uh-KYOO-muhn",
             definition: "Ability to make good judgments",
             sentence: "Her business acumen was impressive.",
             difficulty: .hard),
        Word(word: "Acerbic", pronunciation: "uh-SUR-bik",
             definition: "Sharp or biting in tone",
             sentence: "His acerbic remarks upset everyone.",
             difficulty: .hard),
        Word(word: "Acrimonious", pronunciation: "ak-ri-MOH-nee-uhs",
             definition: "Bitter and angry",
             sentence: "Their acrimonious debate lasted for hours.",
             difficulty: .hard),
        Word(word: "Apocryphal", pronunciation: "uh-PAH-kruh-fuhl",
             definition: "Of doubtful authenticity",
             sentence: "The story was apocryphal but entertaining.",
             difficulty: .hard),
        Word(word: "Arduous", pronunciation: "AHR-joo-uhs",
             definition: "Extremely difficult",
             sentence: "The hike was arduous and exhausting.",
             difficulty: .hard),
        Word(word: "Assiduous", pronunciation: "uh-SID-yoo-uhs",
             definition: "Showing great care and perseverance",
             sentence: "She worked assiduously on her project.",
             difficulty: .hard),
        Word(word: "Benevolent", pronunciation: "buh-NEV-uh-luhnt",
             definition: "Kind and generous",
             sentence: "The benevolent donor funded the school.",
             difficulty: .hard),
        Word(word: "Cacophony", pronunciation: "ka-KOF-uh-nee",
             definition: "A harsh, discordant mixture of sounds",
             sentence: "The city streets were full of cacophony.",
             difficulty: .hard),
        Word(word: "Callipygian", pronunciation: "kal-i-PIJ-ee-uhn",
             definition: "Having well-shaped buttocks",
             sentence: "The statue was callipygian in form.",
             difficulty: .hard),
        Word(word: "Capricious", pronunciation: "kuh-PRISH-uhs",
             definition: "Unpredictable; given to sudden changes",
             sentence: "The weather here is capricious.",
             difficulty: .hard),
        Word(word: "Cognizant", pronunciation: "KOG-ni-zuhnt",
             definition: "Aware; having knowledge",
             sentence: "He was cognizant of the risks involved.",
             difficulty: .hard),
        Word(word: "Conflagration", pronunciation: "kon-fluh-GRAY-shuhn",
             definition: "A large destructive fire",
             sentence: "The forest was destroyed in a conflagration.",
             difficulty: .hard),
        Word(word: "Conundrum", pronunciation: "kuh-NUN-druhm",
             definition: "A confusing and difficult problem",
             sentence: "Solving the puzzle was a conundrum.",
             difficulty: .hard),
        Word(word: "Copious", pronunciation: "KOH-pee-uhs",
             definition: "Abundant in supply",
             sentence: "He took copious notes during the lecture.",
             difficulty: .hard),
        Word(word: "Debacle", pronunciation: "day-BAH-kl",
             definition: "A sudden failure",
             sentence: "The project ended in a debacle.",
             difficulty: .hard),
        Word(word: "Deleterious", pronunciation: "del-i-TEER-ee-uhs",
             definition: "Causing harm",
             sentence: "Smoking has deleterious effects on health.",
             difficulty: .hard),
        Word(word: "Demagogue", pronunciation: "DEM-uh-gog",
             definition: "A leader who appeals to emotions rather than reason",
             sentence: "The demagogue manipulated the public.",
             difficulty: .hard),
        Word(word: "Diaphanous", pronunciation: "dy-AF-uh-nuhs",
             definition: "Light, delicate, translucent",
             sentence: "The dress was made of diaphanous fabric.",
             difficulty: .hard),
        Word(word: "Didactic", pronunciation: "di-DAK-tik",
             definition: "Intended to teach",
             sentence: "The novel was didactic in nature.",
             difficulty: .hard),
        Word(word: "Disparate", pronunciation: "DIS-puh-rit",
             definition: "Essentially different",
             sentence: "The cultures were disparate in traditions.",
             difficulty: .hard),
        Word(word: "Effervescent", pronunciation: "ef-er-VES-uhnt",
             definition: "Bubbly; lively",
             sentence: "Her effervescent personality drew people in.",
             difficulty: .hard),
        Word(word: "Ebullient", pronunciation: "ih-BUL-yuhnt",
             definition: "Full of energy or enthusiasm",
             sentence: "She gave an ebullient speech at the ceremony.",
             difficulty: .hard),
        Word(word: "Egregious", pronunciation: "ih-GREE-juhs",
             definition: "Outstandingly bad",
             sentence: "His egregious mistakes were costly.",
             difficulty: .hard),
        Word(word: "Enervate", pronunciation: "EN-er-vayt",
             definition: "To weaken",
             sentence: "The long journey enervated the soldiers.",
             difficulty: .hard),
        Word(word: "Enigmatic", pronunciation: "en-ig-MAT-ik",
             definition: "Mysterious",
             sentence: "The painting was enigmatic and intriguing.",
             difficulty: .hard),
        Word(word: "Ephemeral", pronunciation: "ih-FEM-er-uhl",
             definition: "Lasting for a very short time",
             sentence: "The beauty of cherry blossoms is ephemeral.",
             difficulty: .hard),
        Word(word: "Equanimity", pronunciation: "ek-wuh-NIM-i-tee",
             definition: "Calmness of mind",
             sentence: "She faced the crisis with equanimity.",
             difficulty: .hard),
        Word(word: "Esoteric", pronunciation: "es-uh-TER-ik",
             definition: "Intended for a small, specialized audience",
             sentence: "The lecture was esoteric and difficult to follow.",
             difficulty: .hard),
        Word(word: "Evanescent", pronunciation: "EV-uh-NES-uhnt",
             definition: "Vanishing quickly",
             sentence: "The rainbow was evanescent after the rain.",
             difficulty: .hard),
        Word(word: "Exacerbate", pronunciation: "ig-ZAS-er-bayt",
             definition: "To make worse",
             sentence: "The delays only exacerbated the problem.",
             difficulty: .hard),
        Word(word: "Exculpate", pronunciation: "EK-skuhl-payt",
             definition: "To clear from blame",
             sentence: "The evidence exculpated him.",
             difficulty: .hard),
        Word(word: "Fastidious", pronunciation: "fas-TID-ee-uhs",
             definition: "Very attentive to detail",
             sentence: "The fastidious chef ensured every dish was perfect.",
             difficulty: .hard),
        Word(word: "Felicity", pronunciation: "fi-LIS-i-tee",
             definition: "Happiness; bliss",
             sentence: "Their wedding was full of felicity.",
             difficulty: .hard),
        Word(word: "Garrulous", pronunciation: "GAR-uh-luhs",
             definition: "Excessively talkative",
             sentence: "The garrulous guide never stopped talking.",
             difficulty: .hard),
        Word(word: "Grandiloquent", pronunciation: "gran-DIL-uh-kwuhnt",
             definition: "Pompous or extravagant in speech",
             sentence: "He spoke in a grandiloquent manner.",
             difficulty: .hard),
        Word(word: "Hackneyed", pronunciation: "HAK-need",
             definition: "Overused, cliched",
             sentence: "The phrase was hackneyed and boring.",
             difficulty: .hard),
        Word(word: "Harangue", pronunciation: "huh-RANG",
             definition: "A lengthy and aggressive speech",
             sentence: "He delivered a harangue to the audience.",
             difficulty: .hard),
        Word(word: "Hegemony", pronunciation: "hi-JEM-uh-nee",
             definition: "Leadership or dominance",
             sentence: "The country's hegemony was challenged.",
             difficulty: .hard),
        Word(word: "Iconoclast", pronunciation: "ai-KON-uh-klast",
             definition: "One who attacks traditions",
             sentence: "He was an iconoclast in the art world.",
             difficulty: .hard),
        Word(word: "Ineffable", pronunciation: "in-EF-uh-buhl",
             definition: "Too great to describe",
             sentence: "The view was ineffable.",
             difficulty: .hard),
        Word(word: "Ineluctable", pronunciation: "in-i-LOOK-tuh-buhl",
             definition: "Impossible to avoid",
             sentence: "The outcome was ineluctable.",
             difficulty: .hard),
        Word(word: "Inimical", pronunciation: "in-IM-i-kuhl",
             definition: "Hostile",
             sentence: "Their policies were inimical to progress.",
             difficulty: .hard),
        Word(word: "Inscrutable", pronunciation: "in-SKROO-tuh-buhl",
             definition: "Impossible to understand",
             sentence: "Her expression was inscrutable.",
             difficulty: .hard),
        Word(word: "Insipid", pronunciation: "in-SIP-id",
             definition: "Lacking flavor or interest",
             sentence: "The soup was insipid.",
             difficulty: .hard),
        Word(word: "Intrepid", pronunciation: "in-TREP-id",
             definition: "Fearless",
             sentence: "The intrepid explorer ventured forward.",
             difficulty: .hard),
        Word(word: "Intransigent", pronunciation: "in-TRAN-si-juhnt",
             definition: "Unwilling to compromise",
             sentence: "Her intransigent attitude frustrated everyone.",
             difficulty: .hard),
        Word(word: "Inveterate", pronunciation: "in-VET-er-it",
             definition: "Long-established habit",
             sentence: "He was an inveterate gambler.",
             difficulty: .hard),
        Word(word: "Irascible", pronunciation: "ih-RAS-uh-buhl",
             definition: "Easily angered",
             sentence: "The irascible teacher scolded students.",
             difficulty: .hard),
        Word(word: "Jocular", pronunciation: "JOK-yuh-luhr",
             definition: "Humorous",
             sentence: "His jocular manner cheered the crowd.",
             difficulty: .hard),
        Word(word: "Juxtapose", pronunciation: "JUHK-stuh-pohz",
             definition: "Place side by side for comparison",
             sentence: "The paintings were juxtaposed in the gallery.",
             difficulty: .hard),
        Word(word: "Laconic", pronunciation: "luh-KON-ik",
             definition: "Using very few words",
             sentence: "His laconic reply suggested annoyance.",
             difficulty: .hard),
        Word(word: "Lugubrious", pronunciation: "loo-GOO-bree-uhs",
             definition: "Looking or sounding sad",
             sentence: "His lugubrious tone alarmed everyone.",
             difficulty: .hard),
        Word(word: "Luminous", pronunciation: "LOO-muh-nuhs",
             definition: "Radiating light",
             sentence: "The luminous moon guided their path.",
             difficulty: .hard),
        Word(word: "Magnanimous", pronunciation: "mag-NAN-uh-muhs",
             definition: "Generous and forgiving",
             sentence: "The magnanimous leader pardoned his rivals.",
             difficulty: .hard),
        Word(word: "Mellifluous", pronunciation: "meh-LIF-loo-uhs",
             definition: "Sweet-sounding",
             sentence: "Her voice was mellifluous.",
             difficulty: .hard),
        Word(word: "Mendacious", pronunciation: "men-DAY-shuhs",
             definition: "Lying",
             sentence: "His mendacious statements were discovered.",
             difficulty: .hard),
        Word(word: "Munificent", pronunciation: "myoo-NIF-uh-suhnt",
             definition: "Extremely generous",
             sentence: "The munificent donor funded the library.",
             difficulty: .hard),
        Word(word: "Nefarious", pronunciation: "neh-FAIR-ee-uhs",
             definition: "Wicked",
             sentence: "The villain’s nefarious plot was foiled.",
             difficulty: .hard),
        Word(word: "Obdurate", pronunciation: "OB-duh-rit",
             definition: "Stubborn",
             sentence: "He remained obdurate despite pleas.",
             difficulty: .hard),
        Word(word: "Obfuscate", pronunciation: "OB-fuh-skayt",
             definition: "To make unclear",
             sentence: "The politician tried to obfuscate the facts.",
             difficulty: .hard),
        Word(word: "Obsequious", pronunciation: "ob-SEE-kwee-uhs",
             definition: "Excessively eager to please",
             sentence: "The obsequious assistant flattered his boss.",
             difficulty: .hard),
        Word(word: "Obstreperous", pronunciation: "ob-STREP-er-uhs",
             definition: "Noisy and difficult",
             sentence: "The obstreperous children ran around.",
             difficulty: .hard),
        Word(word: "Odious", pronunciation: "OH-dee-uhs",
             definition: "Extremely unpleasant",
             sentence: "He committed an odious act.",
             difficulty: .hard),
        Word(word: "Ostentatious", pronunciation: "os-ten-TAY-shuhs",
             definition: "Showy; pretentious",
             sentence: "The ostentatious mansion attracted attention.",
             difficulty: .hard),
        Word(word: "Pernicious", pronunciation: "per-NISH-uhs",
             definition: "Having harmful effect",
             sentence: "The pernicious weed spread rapidly.",
             difficulty: .hard),
        Word(word: "Perspicacious", pronunciation: "pur-spi-KAY-shuhs",
             definition: "Having keen insight",
             sentence: "Her perspicacious analysis helped solve the problem.",
             difficulty: .hard),
        Word(word: "Phlegmatic", pronunciation: "fleg-MAT-ik",
             definition: "Calm and unemotional",
             sentence: "The phlegmatic judge remained neutral.",
             difficulty: .hard),
        Word(word: "Platitudinous", pronunciation: "plat-i-TOO-di-nuhs",
             definition: "Overused and dull",
             sentence: "His speech was platitudinous.",
             difficulty: .hard),
        Word(word: "Polemical", pronunciation: "puh-LEM-i-kuhl",
             definition: "Controversial; argumentative",
             sentence: "The article was polemical and provocative.",
             difficulty: .hard),
        Word(word: "Pernickety", pronunciation: "per-NIK-i-tee",
             definition: "Fussy about small details",
             sentence: "The chef was pernickety about plating.",
             difficulty: .hard),
        Word(word: "Proclivity", pronunciation: "pro-CLIV-i-tee",
             definition: "Natural inclination",
             sentence: "He has a proclivity for painting.",
             difficulty: .hard),
        Word(word: "Propinquity", pronunciation: "proh-PING-kwi-tee",
             definition: "Closeness in relationship",
             sentence: "The propinquity of their offices encouraged collaboration.",
             difficulty: .hard),
        Word(word: "Pusillanimous", pronunciation: "pyoo-suh-LAN-uh-muhs",
             definition: "Timid; lacking courage",
             sentence: "The pusillanimous knight avoided the dragon.",
             difficulty: .hard),
        Word(word: "Quintessential", pronunciation: "kwin-tuh-SEN-shuhl",
             definition: "Most perfect example",
             sentence: "She is the quintessential New Yorker.",
             difficulty: .hard),
        Word(word: "Redolent", pronunciation: "RED-uh-luhnt",
             definition: "Evocative; fragrant",
             sentence: "The kitchen was redolent with spices.",
             difficulty: .hard),
        Word(word: "Redoubtable", pronunciation: "ri-DOU-tuh-buhl",
             definition: "Formidable; worthy of respect",
             sentence: "She was a redoubtable opponent.",
             difficulty: .hard),
        Word(word: "Recalcitrant", pronunciation: "ri-KAL-si-truhnt",
             definition: "Resisting authority",
             sentence: "The recalcitrant student refused to cooperate.",
             difficulty: .hard),
        Word(word: "Reprobate", pronunciation: "REP-ruh-bayt",
             definition: "Morally unprincipled person",
             sentence: "He was a reprobate in the eyes of society.",
             difficulty: .hard),
        Word(word: "Sagacious", pronunciation: "suh-GAY-shuhs",
             definition: "Wise; showing good judgment",
             sentence: "Her sagacious advice helped me make the decision.",
             difficulty: .hard),
        Word(word: "Sanguine", pronunciation: "SAN-gwin",
             definition: "Optimistic or positive",
             sentence: "He remained sanguine despite setbacks.",
             difficulty: .hard),
        Word(word: "Supercilious", pronunciation: "soo-per-SIL-ee-uhs",
             definition: "Arrogant or condescending",
             sentence: "The supercilious waiter ignored the guests.",
             difficulty: .hard),
        Word(word: "Tantamount", pronunciation: "TAN-tuh-mount",
             definition: "Equivalent in effect or value",
             sentence: "His refusal was tantamount to an admission of guilt.",
             difficulty: .hard),
        Word(word: "Trepidation", pronunciation: "trep-i-DAY-shuhn",
             definition: "Fear or anxiety",
             sentence: "He approached the stage with trepidation.",
             difficulty: .hard),
        Word(word: "Ubiquitous", pronunciation: "yoo-BIK-wi-tuhs",
             definition: "Present everywhere",
             sentence: "Smartphones are ubiquitous these days.",
             difficulty: .hard),
        Word(word: "Unctuous", pronunciation: "UNK-choo-uhs",
             definition: "Excessively flattering; oily",
             sentence: "The salesman had an unctuous manner.",
             difficulty: .hard),
        Word(word: "Vacillate", pronunciation: "VAS-i-layt",
             definition: "To waver in mind or opinion",
             sentence: "He vacillated between choices.",
             difficulty: .hard),
        Word(word: "Venerable", pronunciation: "VEN-uh-ruh-buhl",
             definition: "Commanding respect",
             sentence: "The venerable teacher was admired by all.",
             difficulty: .hard),
        Word(word: "Veracity", pronunciation: "vuh-RAS-i-tee",
             definition: "Truthfulness",
             sentence: "We doubted the veracity of his claim.",
             difficulty: .hard),
        Word(word: "Vicissitude", pronunciation: "vi-SIS-i-tood",
             definition: "A change or variation",
             sentence: "Life is full of vicissitudes.",
             difficulty: .hard),
        Word(word: "Vindicate", pronunciation: "VIN-di-kayt",
             definition: "To clear of blame",
             sentence: "The evidence vindicated her.",
             difficulty: .hard),
        Word(word: "Vociferous", pronunciation: "voh-SIF-er-uhs",
             definition: "Loud and forceful",
             sentence: "The vociferous crowd demanded answers.",
             difficulty: .hard),
        Word(word: "Voracious", pronunciation: "voh-RAY-shuhs",
             definition: "Having a huge appetite",
             sentence: "He was a voracious reader.",
             difficulty: .hard),
        Word(word: "Winsome", pronunciation: "WIN-sum",
             definition: "Attractive or appealing",
             sentence: "Her winsome smile charmed everyone.",
             difficulty: .hard),
        Word(word: "Zephyr", pronunciation: "ZEF-er",
             definition: "A gentle breeze",
             sentence: "A zephyr cooled the afternoon heat.",
             difficulty: .hard)
    ]
}
