// Models/Word.swift
import Foundation

struct Word: Identifiable, Codable, Equatable {
    var id = UUID()                    // ← make it var, not let
    let word: String
    let pronunciation: String
    let definition: String
    let sentence: String
    
    static let sampleWords: [Word] = [
        Word(word: "Ephemeral", pronunciation: "ih-FEM-er-uhl",
             definition: "Lasting for a very short time",
             sentence: "The beauty of cherry blossoms is ephemeral."),
        Word(word: "Serendipity", pronunciation: "ser-en-DIP-i-tee",
             definition: "Finding something good without looking for it",
             sentence: "Meeting you here was pure serendipity."),
        Word(word: "Quintessential", pronunciation: "kwin-tuh-SEN-shuhl",
             definition: "Representing the most perfect example",
             sentence: "She is the quintessential New Yorker."),
        Word(word: "Eloquent", pronunciation: "EL-uh-kwuhnt",
             definition: "Fluent and persuasive in speaking",
             sentence: "His eloquent speech moved the audience."),
        Word(word: "Ubiquitous", pronunciation: "yoo-BIK-wi-tuhs",
             definition: "Present everywhere",
             sentence: "Smartphones are now ubiquitous."),
        Word(word: "Mellifluous", pronunciation: "meh-LIF-loo-uhs",
             definition: "Sweet-sounding or smooth",
             sentence: "Her voice was mellifluous and calming."),
        Word(word: "Obfuscate", pronunciation: "OB-fuh-skayt",
             definition: "To make something unclear",
             sentence: "The politician tried to obfuscate the facts."),
        Word(word: "Pernicious", pronunciation: "per-NISH-uhs",
             definition: "Having a harmful effect",
             sentence: "The pernicious weed spread throughout the garden."),
        Word(word: "Ineffable", pronunciation: "in-EF-uh-buhl",
             definition: "Too great for words",
             sentence: "The beauty of the sunset was ineffable."),
        Word(word: "Cacophony", pronunciation: "ka-KOF-uh-nee",
             definition: "A harsh, discordant mixture of sounds",
             sentence: "The city streets were full of cacophony."),
        Word(word: "Luminous", pronunciation: "LOO-muh-nuhs",
             definition: "Radiating or reflecting light",
             sentence: "The luminous moon guided their path."),
        Word(word: "Resplendent", pronunciation: "ri-SPLEN-duhnt",
             definition: "Shining brilliantly; gorgeous",
             sentence: "She entered the ballroom looking resplendent."),
        Word(word: "Voracious", pronunciation: "vo-RAY-shuhs",
             definition: "Having a huge appetite or enthusiasm",
             sentence: "He is a voracious reader of mystery novels."),
        Word(word: "Sagacious", pronunciation: "suh-GAY-shuhs",
             definition: "Wise; showing good judgment",
             sentence: "Her sagacious advice helped me make the decision."),
        Word(word: "Obsequious", pronunciation: "ob-SEE-kwee-uhs",
             definition: "Excessively eager to please",
             sentence: "The obsequious assistant flattered his boss constantly."),
        Word(word: "Pulchritude", pronunciation: "PUL-kri-tood",
             definition: "Physical beauty",
             sentence: "The model’s pulchritude was undeniable."),
        Word(word: "Irascible", pronunciation: "ih-RAS-uh-buhl",
             definition: "Easily angered",
             sentence: "The irascible teacher scolded students for minor mistakes."),
        Word(word: "Ebullient", pronunciation: "ih-BUL-yuhnt",
             definition: "Full of energy or enthusiasm",
             sentence: "She gave an ebullient speech at the ceremony."),
        Word(word: "Laconic", pronunciation: "luh-KON-ik",
             definition: "Using very few words",
             sentence: "His laconic reply suggested he was annoyed."),
        Word(word: "Obdurate", pronunciation: "OB-duh-rit",
             definition: "Stubborn; unyielding",
             sentence: "He remained obdurate despite everyone’s pleas."),
        Word(word: "Pusillanimous", pronunciation: "pyoo-suh-LAN-uh-muhs",
             definition: "Timid; lacking courage",
             sentence: "The pusillanimous knight avoided the dragon."),
        Word(word: "Munificent", pronunciation: "myoo-NIF-uh-suhnt",
             definition: "Extremely generous",
             sentence: "The munificent donor funded the new library."),
        Word(word: "Sycophant", pronunciation: "SIS-uh-fant",
             definition: "A person who flatters others for personal gain",
             sentence: "The office sycophant always agreed with the boss."),
        Word(word: "Indefatigable", pronunciation: "in-di-FAT-i-guh-buhl",
             definition: "Tireless; persistent",
             sentence: "Her indefatigable spirit inspired the team."),
        Word(word: "Tantamount", pronunciation: "TAN-tuh-mount",
             definition: "Equivalent in effect or value",
             sentence: "His refusal was tantamount to an admission of guilt."),
        Word(word: "Epistolary", pronunciation: "ih-PIS-tuh-lair-ee",
             definition: "Relating to letters or correspondence",
             sentence: "The novel was written in an epistolary style."),
        Word(word: "Exacerbate", pronunciation: "ig-ZAS-er-bayt",
             definition: "To make worse",
             sentence: "The delays only exacerbated the problem."),
        Word(word: "Oblivious", pronunciation: "uh-BLIV-ee-uhs",
             definition: "Unaware of what is happening",
             sentence: "He was oblivious to the chaos around him."),
        Word(word: "Fastidious", pronunciation: "fas-TID-ee-uhs",
             definition: "Very attentive to detail",
             sentence: "The fastidious chef ensured every dish was perfect."),
        Word(word: "Intransigent", pronunciation: "in-TRAN-si-juhnt",
             definition: "Unwilling to compromise",
             sentence: "Her intransigent attitude frustrated everyone."),
        Word(word: "Nefarious", pronunciation: "neh-FAIR-ee-uhs",
             definition: "Wicked or criminal",
             sentence: "The villain’s nefarious plot was foiled."),
        Word(word: "Exculpate", pronunciation: "EK-skuhl-payt",
             definition: "To clear from blame",
             sentence: "The evidence exculpated him."),
        Word(word: "Recalcitrant", pronunciation: "ri-KAL-si-truhnt",
             definition: "Resisting authority or control",
             sentence: "The recalcitrant student refused to cooperate."),
        Word(word: "Mendacious", pronunciation: "men-DAY-shuhs",
             definition: "Lying; untruthful",
             sentence: "His mendacious statements were discovered."),
        Word(word: "Sagacity", pronunciation: "suh-GAS-i-tee",
             definition: "Wisdom",
             sentence: "The council relied on his sagacity."),
        Word(word: "Temerity", pronunciation: "tuh-MER-i-tee",
             definition: "Excessive boldness",
             sentence: "She had the temerity to challenge the mayor."),
        Word(word: "Vociferous", pronunciation: "vo-SIF-er-uhs",
             definition: "Loud and forceful",
             sentence: "The vociferous crowd demanded answers."),
        Word(word: "Obstreperous", pronunciation: "ob-STREP-er-uhs",
             definition: "Noisy and difficult to control",
             sentence: "The obstreperous children ran through the store."),
        Word(word: "Inimical", pronunciation: "in-IM-i-kuhl",
             definition: "Hostile or harmful",
             sentence: "Their policies were inimical to progress."),
        Word(word: "Redolent", pronunciation: "RED-uh-luhnt",
             definition: "Evocative; fragrant",
             sentence: "The kitchen was redolent with spices."),
        Word(word: "Penurious", pronunciation: "puh-NYOOR-ee-uhs",
             definition: "Extremely poor",
             sentence: "The penurious artist struggled to pay rent."),
        Word(word: "Abstruse", pronunciation: "ab-STRUSE",
             definition: "Difficult to understand",
             sentence: "The theory was abstruse for most students."),
        Word(word: "Recondite", pronunciation: "REK-un-dyt",
             definition: "Little known; obscure",
             sentence: "His recondite knowledge impressed scholars."),
        Word(word: "Phlegmatic", pronunciation: "fleg-MAT-ik",
             definition: "Calm and unemotional",
             sentence: "The phlegmatic judge remained neutral."),
        Word(word: "Propinquity", pronunciation: "proh-PING-kwi-tee",
             definition: "Closeness in relationship",
             sentence: "The propinquity of their offices encouraged collaboration."),
        Word(word: "Supercilious", pronunciation: "soo-per-SIL-ee-uhs",
             definition: "Arrogant or condescending",
             sentence: "The supercilious waiter ignored the guests."),
        Word(word: "Pulverize", pronunciation: "PUHL-vuh-ryz",
             definition: "To crush or grind to powder",
             sentence: "The machine will pulverize the grains quickly."),
        Word(word: "Acrimonious", pronunciation: "ak-ri-MOH-nee-uhs",
             definition: "Bitter and angry",
             sentence: "Their acrimonious debate lasted for hours."),
        Word(word: "Munificence", pronunciation: "myoo-NIF-i-suhns",
             definition: "Generosity",
             sentence: "The foundation is known for its munificence."),
        Word(word: "Callipygian", pronunciation: "kal-i-PIJ-ee-uhn",
             definition: "Having well-shaped buttocks",
             sentence: "The statue was callipygian in form."),
        Word(word: "Sanguine", pronunciation: "SAN-gwin",
             definition: "Optimistic or positive",
             sentence: "He remained sanguine despite setbacks."),
        Word(word: "Inchoate", pronunciation: "in-KOH-ayt",
             definition: "Just begun; undeveloped",
             sentence: "Their plan was still inchoate."),
        Word(word: "Apocryphal", pronunciation: "uh-PAH-kruh-fuhl",
             definition: "Of doubtful authenticity",
             sentence: "The story was apocryphal but entertaining."),
        Word(word: "Evanescent", pronunciation: "EV-uh-NES-uhnt",
             definition: "Vanishing quickly",
             sentence: "The rainbow was evanescent after the rain."),
        Word(word: "Enervate", pronunciation: "EN-er-vayt",
             definition: "To weaken",
             sentence: "The long journey enervated the soldiers."),
        Word(word: "Lugubrious", pronunciation: "loo-GOO-bree-uhs",
             definition: "Looking or sounding sad",
             sentence: "His lugubrious tone alarmed everyone."),
        Word(word: "Phantasmagorical", pronunciation: "fan-taz-muh-GOR-i-kuhl",
             definition: "Surreal; dreamlike",
             sentence: "The carnival felt phantasmagorical."),
        Word(word: "Insipid", pronunciation: "in-SIP-id",
             definition: "Lacking flavor or interest",
             sentence: "The soup was insipid and bland."),
        Word(word: "Parsimonious", pronunciation: "par-si-MO-nee-uhs",
             definition: "Extremely frugal",
             sentence: "He was parsimonious with his money."),
        Word(word: "Redoubtable", pronunciation: "ri-DOU-tuh-buhl",
             definition: "Formidable; worthy of respect",
             sentence: "She was a redoubtable opponent."),
        Word(word: "Recalcitrance", pronunciation: "ri-KAL-si-truhns",
             definition: "Stubborn resistance",
             sentence: "The recalcitrance of the team delayed progress."),
        Word(word: "Peregrinate", pronunciation: "PER-uh-gri-nayt",
             definition: "To travel or wander",
             sentence: "They peregrinated across Europe last summer."),
        Word(word: "Obfuscation", pronunciation: "OB-fuh-SKAY-shuhn",
             definition: "Act of making unclear",
             sentence: "His speech was full of obfuscation."),
        Word(word: "Impetuous", pronunciation: "im-PECH-oo-uhs",
             definition: "Acting quickly without thought",
             sentence: "Her impetuous decision caused problems."),
        Word(word: "Reprobate", pronunciation: "REP-ruh-bayt",
             definition: "Morally unprincipled person",
             sentence: "He was a reprobate in the eyes of society."),
        Word(word: "Trepidation", pronunciation: "trep-i-DAY-shuhn",
             definition: "Fear or anxiety",
             sentence: "He approached the stage with trepidation."),
        Word(word: "Vociferate", pronunciation: "vo-SIF-er-ayt",
             definition: "To shout or yell",
             sentence: "The coach vociferated instructions."),
        Word(word: "Auspicious", pronunciation: "aw-SPISH-uhs",
             definition: "Favorable; promising",
             sentence: "The ceremony began under auspicious conditions."),
        Word(word: "Exigent", pronunciation: "EK-si-juhnt",
             definition: "Urgent; requiring immediate action",
             sentence: "The exigent matter needed quick resolution."),
        Word(word: "Inexorable", pronunciation: "in-EK-ser-uh-buhl",
             definition: "Impossible to stop or prevent",
             sentence: "The inexorable march of time continues."),
        Word(word: "Perfunctory", pronunciation: "per-FUNK-tuh-ree",
             definition: "Done with minimal effort",
             sentence: "His perfunctory nod showed disinterest."),
        Word(word: "Superfluous", pronunciation: "soo-PER-floo-uhs",
             definition: "Unnecessary; excessive",
             sentence: "Remove superfluous words from the text."),
        Word(word: "Acerbic", pronunciation: "uh-SUR-bik",
             definition: "Sharp or biting in tone",
             sentence: "Her acerbic comments stung."),
        Word(word: "Pernickety", pronunciation: "per-NIK-i-tee",
             definition: "Fussy about small details",
             sentence: "The chef was pernickety about plating."),
        Word(word: "Munificently", pronunciation: "myoo-NIF-i-suhnt-lee",
             definition: "Generously",
             sentence: "She donated munificently to charity."),
        Word(word: "Insouciant", pronunciation: "in-SOO-see-uhnt",
             definition: "Carefree; unconcerned",
             sentence: "He wandered insouciant through the streets."),
        Word(word: "Ineffably", pronunciation: "in-EF-uh-blee",
             definition: "In a way too great to be expressed",
             sentence: "The beauty was ineffably breathtaking."),
        Word(word: "Refulgent", pronunciation: "ri-FUL-juhnt",
             definition: "Shining brightly",
             sentence: "The refulgent sunlight illuminated the valley."),
        Word(word: "Felicity", pronunciation: "fi-LIS-i-tee",
             definition: "Happiness; bliss",
             sentence: "Their wedding was full of felicity."),
        Word(word: "Garrulous", pronunciation: "GAR-uh-luhs",
             definition: "Excessively talkative",
             sentence: "The garrulous guide never stopped talking."),
        Word(word: "Pulchritudinous", pronunciation: "puhl-kri-TOO-di-nuhs",
             definition: "Physically beautiful",
             sentence: "The actress was pulchritudinous."),
        Word(word: "Pugnacious", pronunciation: "puhg-NAY-shuhs",
             definition: "Eager to fight",
             sentence: "The pugnacious boxer challenged everyone."),
        Word(word: "Tantamountly", pronunciation: "TAN-tuh-mount-lee",
             definition: "Equivalent in effect",
             sentence: "Her silence was tantamountly an admission."),
        Word(word: "Sanguinely", pronunciation: "SAN-gwin-lee",
             definition: "Optimistically",
             sentence: "He faced the challenges sanguinely."),
        Word(word: "Perspicacious", pronunciation: "pur-spi-KAY-shuhs",
             definition: "Having keen insight",
             sentence: "Her perspicacious analysis helped solve the problem."),
        Word(word: "Incontrovertible", pronunciation: "in-kon-truh-VUR-tuh-buhl",
             definition: "Impossible to dispute",
             sentence: "The evidence was incontrovertible."),
        Word(word: "Perniciously", pronunciation: "per-NISH-uhs-lee",
             definition: "Harmfully",
             sentence: "The poison spread perniciously."),
        Word(word: "Obsequiously", pronunciation: "ob-SEE-kwee-uhs-lee",
             definition: "Excessively obedient or attentive",
             sentence: "He obsequiously followed orders."),
        Word(word: "Vicissitude", pronunciation: "vi-SIS-i-tood",
             definition: "A change of circumstances",
             sentence: "Life is full of vicissitudes."),
        Word(word: "Inefficiency", pronunciation: "in-ef-ISH-en-see",
             definition: "Lack of efficiency",
             sentence: "The project suffered from inefficiency."),
        Word(word: "Ebullience", pronunciation: "ih-BUL-yuhns",
             definition: "High spirits",
             sentence: "Her ebullience was contagious."),
        Word(word: "Lugubriously", pronunciation: "loo-GOO-bree-uhs-lee",
             definition: "In a mournful way",
             sentence: "He sighed lugubriously."),
        Word(word: "Perspicuity", pronunciation: "pur-spi-KYOO-i-tee",
             definition: "Clearness",
             sentence: "The perspicuity of his writing is remarkable."),
        Word(word: "Rapprochement", pronunciation: "ra-prosh-MAHN",
             definition: "Reconciliation",
             sentence: "The countries reached a rapprochement."),
        Word(word: "Platitudinous", pronunciation: "plat-i-TOO-di-nuhs",
             definition: "Overused and dull",
             sentence: "His speech was platitudinous."),
        Word(word: "Obstreperously", pronunciation: "ob-STREP-er-uhs-lee",
             definition: "Noisily resistant",
             sentence: "The students protested obstreperously."),
        Word(word: "Indefatigably", pronunciation: "in-di-FAT-i-guh-bly",
             definition: "Without tiring",
             sentence: "She worked indefatigably."),
        Word(word: "Inveterate", pronunciation: "in-VET-er-it",
             definition: "Long-established",
             sentence: "He is an inveterate gambler."),
        Word(word: "Proclivity", pronunciation: "pro-CLIV-i-tee",
             definition: "A natural inclination",
             sentence: "He has a proclivity for painting."),
        Word(word: "Inimitable", pronunciation: "in-IM-i-tuh-buhl",
             definition: "Unique; impossible to imitate",
             sentence: "Her style is inimitable."),
        Word(word: "Mellifluously", pronunciation: "meh-LIF-loo-uhs-lee",
             definition: "Sweetly",
             sentence: "She spoke mellifluously."),
        Word(word: "Venerable", pronunciation: "VEN-er-uh-buhl",
             definition: "Respected because of age",
             sentence: "The venerable scholar taught for decades."),
        Word(word: "Sagaciously", pronunciation: "suh-GAY-shuhs-lee",
             definition: "Wisely",
             sentence: "He acted sagaciously."),
        Word(word: "Recalcitrantly", pronunciation: "ri-KAL-si-truhnt-lee",
             definition: "Stubbornly",
             sentence: "The team rebelled recalcitrantly."),
        Word(word: "Superciliously", pronunciation: "soo-per-SIL-ee-uhs-lee",
             definition: "Arrogantly",
             sentence: "He spoke superciliously."),
        Word(word: "Prosaically", pronunciation: "pro-ZAY-ik-lee",
             definition: "Dully",
             sentence: "The novel ended prosaically."),
        Word(word: "Improvident", pronunciation: "im-PROV-i-duhnt",
             definition: "Not careful with resources",
             sentence: "His improvident spending led to debt."),
        Word(word: "Exonerate", pronunciation: "ig-ZON-uh-rayt",
             definition: "To free from blame",
             sentence: "The evidence exonerated the defendant."),
        Word(word: "Pulchritudinously", pronunciation: "puhl-kri-TOO-di-nuhs-lee",
             definition: "Beautifully",
             sentence: "The actress was pulchritudinously dressed."),
        Word(word: "Impetuously", pronunciation: "im-PECH-oo-uhs-lee",
             definition: "Acting rashly",
             sentence: "He acted impetuously in the market."),
        Word(word: "Unctuous", pronunciation: "UNGK-choo-uhs",
             definition: "Excessively flattering",
             sentence: "The salesman was unctuous."),
        Word(word: "Rambunctious", pronunciation: "ram-BUNK-shuhs",
             definition: "Unruly; energetic",
             sentence: "The rambunctious kids ran around the yard."),
        Word(word: "Inchoately", pronunciation: "in-KOH-ayt-lee",
             definition: "In an initial stage",
             sentence: "The plan was inchoately formed."),
        Word(word: "Abstrusely", pronunciation: "ab-STRUSE-lee",
             definition: "In a difficult to understand manner",
             sentence: "He explained abstrusely."),
        Word(word: "Perspicaciously", pronunciation: "pur-spi-KAY-shuhs-lee",
             definition: "With insight",
             sentence: "She analyzed perspicaciously."),
        Word(word: "Irascibly", pronunciation: "ih-RAS-uh-bly",
             definition: "Angrily",
             sentence: "He reacted irascibly."),
        Word(word: "Trepidatiously", pronunciation: "trep-i-DAY-shuhs-lee",
             definition: "With fear",
             sentence: "She stepped trepidatiously."),
        Word(word: "Pulverously", pronunciation: "PUHL-vuh-ruhs-lee",
             definition: "Into powder",
             sentence: "The spices were ground pulverously."),
        Word(word: "Acerbically", pronunciation: "uh-SUR-bik-lee",
             definition: "Sharply",
             sentence: "She spoke acerbically."),
        Word(word: "Vociferously", pronunciation: "vo-SIF-er-uhs-lee",
             definition: "Loudly",
             sentence: "The protesters shouted vociferously."),
        Word(word: "Insipidly", pronunciation: "in-SIP-id-lee",
             definition: "Dully",
             sentence: "The soup tasted insipidly."),
        Word(word: "Exigently", pronunciation: "EK-si-juhnt-lee",
             definition: "Urgently",
             sentence: "The issue had to be addressed exigently."),
        Word(word: "Reprobately", pronunciation: "REP-ruh-bayt-lee",
             definition: "Morally unprincipled",
             sentence: "He acted reprobately."),
        Word(word: "Tantamountly", pronunciation: "TAN-tuh-mount-lee",
             definition: "Equivalent",
             sentence: "Her refusal was tantamountly a denial."),
        Word(word: "Indefatigably", pronunciation: "in-di-FAT-i-guh-bly",
             definition: "Without tiring",
             sentence: "She worked indefatigably for the cause."),
        Word(word: "Callipygianly", pronunciation: "kal-i-PIJ-ee-uhn-lee",
             definition: "Having well-shaped buttocks",
             sentence: "The statue was callipygianly proportioned."),
        Word(word: "Abstruseness", pronunciation: "ab-STRUSE-ness",
             definition: "Difficulty to understand",
             sentence: "His explanation was full of abstruseness."),
        Word(word: "Sycophantically", pronunciation: "SIS-uh-fant-ik-lee",
             definition: "In a flattering way",
             sentence: "He followed sycophantically."),
        Word(word: "Intransigently", pronunciation: "in-TRAN-si-juhnt-lee",
             definition: "Unwilling to compromise",
             sentence: "The committee acted intransigently."),
        Word(word: "Vicissitudinous", pronunciation: "vi-SIS-i-TOO-di-nuhs",
             definition: "Full of changes",
             sentence: "Life is vicissitudinous."),
        Word(word: "Exculpatory", pronunciation: "EK-skuhl-puh-tor-ee",
             definition: "Clearing from blame",
             sentence: "The new evidence was exculpatory."),
        Word(word: "Refulgently", pronunciation: "ri-FUL-juhnt-lee",
             definition: "Shining brightly",
             sentence: "The sun shone refulgently."),
        Word(word: "Superfluously", pronunciation: "soo-PER-floo-uhs-lee",
             definition: "Excessively",
             sentence: "He spoke superfluously."),
        Word(word: "Luminously", pronunciation: "LOO-muh-nuhs-lee",
             definition: "Radiantly",
             sentence: "The lantern shone luminously."),
        Word(word: "Inveterately", pronunciation: "in-VET-er-it-lee",
             definition: "Long-established",
             sentence: "He gambled inveterately."),
        Word(word: "Perniciously", pronunciation: "per-NISH-uhs-lee",
             definition: "Harmfully",
             sentence: "The rumor spread perniciously."),
        Word(word: "Inexorably", pronunciation: "in-EK-ser-uh-blee",
             definition: "Relentlessly",
             sentence: "Time moves inexorably."),
        Word(word: "Improvidently", pronunciation: "im-PROV-i-duhnt-lee",
             definition: "Without care",
             sentence: "He spent improvidently."),
        Word(word: "Obdurately", pronunciation: "OB-duh-rit-lee",
             definition: "Stubbornly",
             sentence: "He refused obdurately."),
        Word(word: "Pulverizably", pronunciation: "PUHL-vuh-ry-zuh-blee",
             definition: "Able to be crushed to powder",
             sentence: "The grains were pulverizably crushed."),
        Word(word: "Lugubriousness", pronunciation: "loo-GOO-bree-uhs-ness",
             definition: "Mournfulness",
             sentence: "His lugubriousness was evident."),
        Word(word: "Vociferously", pronunciation: "vo-SIF-er-uhs-lee",
             definition: "Loudly",
             sentence: "They protested vociferously."),
        Word(word: "Perspicuously", pronunciation: "pur-SPI-kyoo-uhs-lee",
             definition: "Clearly",
             sentence: "He explained perspicuously."),
        Word(word: "Exigent", pronunciation: "EK-si-juhnt",
             definition: "Urgent",
             sentence: "The exigent situation demanded action."),
        Word(word: "Sagaciousness", pronunciation: "suh-GAY-shuhs-ness",
             definition: "Wisdom",
             sentence: "The sage was known for his sagaciousness."),
        Word(word: "Eloquent", pronunciation: "EL-uh-kwuhnt",
             definition: "Fluent and persuasive",
             sentence: "Her eloquent speech impressed all."),
        Word(word: "Intransigence", pronunciation: "in-TRAN-si-juhns",
             definition: "Refusal to compromise",
             sentence: "His intransigence caused delays."),
        Word(word: "Insouciantly", pronunciation: "in-SOO-see-uhnt-lee",
             definition: "Carefree",
             sentence: "She wandered insouciantly."),
        Word(word: "Munificently", pronunciation: "myoo-NIF-i-suhnt-lee",
             definition: "Generously",
             sentence: "The donor gave munificently."),
        Word(word: "Redolently", pronunciation: "RED-uh-luhnt-lee",
             definition: "Fragrantly",
             sentence: "The room smelled redolently."),
        Word(word: "Pusillanimously", pronunciation: "pyoo-suh-LAN-i-muhs-lee",
             definition: "Timidly",
             sentence: "He approached pusillanimously."),
        Word(word: "Obsequiously", pronunciation: "ob-SEE-kwee-uhs-lee",
             definition: "Flatteringly",
             sentence: "He followed obsequiously."),
        Word(word: "Pulchritudinously", pronunciation: "puhl-kri-TOO-di-nuhs-lee",
             definition: "Beautifully",
             sentence: "She was pulchritudinously dressed."),
        Word(word: "Superciliously", pronunciation: "soo-per-SIL-ee-uhs-lee",
             definition: "Arrogantly",
             sentence: "He behaved superciliously."),
        Word(word: "Phlegmatically", pronunciation: "fleg-MAT-ik-lee",
             definition: "Calmly",
             sentence: "He responded phlegmatically."),
        Word(word: "Quintessentially", pronunciation: "kwin-tuh-SEN-shuh-lee",
             definition: "In an ideal manner",
             sentence: "She performed quintessentially."),
        Word(word: "Vociferously", pronunciation: "vo-SIF-er-uhs-lee",
             definition: "Loudly",
             sentence: "The crowd vociferously protested."),
        Word(word: "Ineffably", pronunciation: "in-EF-uh-blee",
             definition: "Indescribably",
             sentence: "The scene was ineffably beautiful."),
        Word(word: "Sagaciously", pronunciation: "suh-GAY-shuhs-lee",
             definition: "Wisely",
             sentence: "He acted sagaciously."),
        Word(word: "Obstreperously", pronunciation: "ob-STREP-er-uhs-lee",
             definition: "Noisily",
             sentence: "The children behaved obstreperously."),
        Word(word: "Mendaciously", pronunciation: "men-DAY-shuhs-lee",
             definition: "Dishonestly",
             sentence: "He spoke mendaciously."),
        Word(word: "Trepidatiously", pronunciation: "trep-i-DAY-shuhs-lee",
             definition: "Fearfully",
             sentence: "She moved trepidatiously."),
        Word(word: "Inimically", pronunciation: "in-IM-i-kuhl-lee",
             definition: "Hostilely",
             sentence: "They acted inimically."),
        Word(word: "Perniciously", pronunciation: "per-NISH-uhs-lee",
             definition: "Harmfully",
             sentence: "The rumor spread perniciously."),
        Word(word: "Recalcitrantly", pronunciation: "ri-KAL-si-truhnt-lee",
             definition: "Stubbornly",
             sentence: "He rebelled recalcitrantly."),
        Word(word: "Pulverizably", pronunciation: "PUHL-vuh-ry-zuh-blee",
             definition: "Crushable to powder",
             sentence: "The grains were pulverizably crushed."),
        Word(word: "Lugubriously", pronunciation: "loo-GOO-bree-uhs-lee",
             definition: "Mournfully",
             sentence: "He sighed lugubriously."),
        Word(word: "Inexorably", pronunciation: "in-EK-ser-uh-blee",
             definition: "Relentlessly",
             sentence: "Time passes inexorably."),
        Word(word: "Superfluously", pronunciation: "soo-PER-floo-uhs-lee",
             definition: "Excessively",
             sentence: "He spoke superfluously."),
        Word(word: "Exculpatorily", pronunciation: "EK-skuhl-puh-tor-uh-lee",
             definition: "To free from blame",
             sentence: "He was exculpatorily cleared."),
        Word(word: "Ebulliently", pronunciation: "ih-BUL-yuhnt-lee",
             definition: "Energetically",
             sentence: "She danced ebulliently."),
        Word(word: "Redoubtable", pronunciation: "ri-DOU-tuh-buhl",
             definition: "Formidable",
             sentence: "The champion was redoubtable."),
        Word(word: "Inimitably", pronunciation: "in-IM-i-tuh-bly",
             definition: "Uniquely",
             sentence: "She performed inimitably."),
        Word(word: "Pusillanimously", pronunciation: "pyoo-suh-LAN-i-muhs-lee",
             definition: "Timidly",
             sentence: "He approached pusillanimously."),
        Word(word: "Intransigently", pronunciation: "in-TRAN-si-juhnt-lee",
             definition: "Uncompromisingly",
             sentence: "The council acted intransigently."),
        Word(word: "Redolently", pronunciation: "RED-uh-luhnt-lee",
             definition: "Fragrantly",
             sentence: "The kitchen was redolently scented."),
        Word(word: "Luminously", pronunciation: "LOO-muh-nuhs-lee",
             definition: "Brightly",
             sentence: "The stars shone luminously."),
        Word(word: "Vicissitudinously", pronunciation: "vi-SIS-i-TOO-di-nuhs-lee",
             definition: "With frequent changes",
             sentence: "Life changes vicissitudinously."),
        Word(word: "Evanescently", pronunciation: "EV-uh-NES-uhnt-lee",
             definition: "Briefly",
             sentence: "The rainbow appeared evanescently."),
        Word(word: "Ineffably", pronunciation: "in-EF-uh-blee",
             definition: "Indescribably",
             sentence: "The view was ineffably stunning."),
        Word(word: "Sagaciously", pronunciation: "suh-GAY-shuhs-lee",
             definition: "Wisely",
             sentence: "He acted sagaciously."),
        Word(word: "Obstreperously", pronunciation: "ob-STREP-er-uhs-lee",
             definition: "Noisily",
             sentence: "The protesters acted obstreperously."),
        Word(word: "Mellifluously", pronunciation: "meh-LIF-loo-uhs-lee",
             definition: "Smoothly",
             sentence: "She sang mellifluously."),
        Word(word: "Vociferously", pronunciation: "vo-SIF-er-uhs-lee",
             definition: "Loudly",
             sentence: "They argued vociferously."),
        Word(word: "Recalcitrantly", pronunciation: "ri-KAL-si-truhnt-lee",
             definition: "Stubbornly",
             sentence: "The student acted recalcitrantly."),
        Word(word: "Inexorably", pronunciation: "in-EK-ser-uh-blee",
             definition: "Relentlessly",
             sentence: "Time moves inexorably."),
        Word(word: "Improvidently", pronunciation: "im-PROV-i-duhnt-lee",
             definition: "Carelessly",
             sentence: "He spent improvidently."),
        Word(word: "Abstrusely", pronunciation: "ab-STRUSE-lee",
             definition: "Difficult to understand",
             sentence: "He wrote abstrusely."),
        Word(word: "Phlegmatically", pronunciation: "fleg-MAT-ik-lee",
             definition: "Calmly",
             sentence: "He responded phlegmatically."),
        Word(word: "Exculpatorily", pronunciation: "EK-skuhl-puh-tor-uh-lee",
             definition: "Clearing blame",
             sentence: "The evidence exculpatorily cleared him."),
        Word(word: "Trepidatiously", pronunciation: "trep-i-DAY-shuhs-lee",
             definition: "Fearfully",
             sentence: "She moved trepidatiously."),
        Word(word: "Redoubtable", pronunciation: "ri-DOU-tuh-buhl",
             definition: "Formidable",
             sentence: "The opponent was redoubtable."),
        Word(word: "Sanguinely", pronunciation: "SAN-gwin-lee",
             definition: "Optimistically",
             sentence: "He faced the challenge sanguinely."),
        Word(word: "Pulchritudinously", pronunciation: "puhl-kri-TOO-di-nuhs-lee",
             definition: "Beautifully",
             sentence: "The model was pulchritudinously dressed."),
        Word(word: "Indefatigably", pronunciation: "in-di-FAT-i-guh-bly",
             definition: "Without tiring",
             sentence: "She worked indefatigably."),
        Word(word: "Ebulliently", pronunciation: "ih-BUL-yuhnt-lee",
             definition: "Energetically",
             sentence: "The children played ebulliently."),
        Word(word: "Inveterately", pronunciation: "in-VET-er-it-lee",
             definition: "Habitually",
             sentence: "He gambled inveterately."),
        Word(word: "Mendaciously", pronunciation: "men-DAY-shuhs-lee",
             definition: "Dishonestly",
             sentence: "He spoke mendaciously."),
        Word(word: "Obsequiously", pronunciation: "ob-SEE-kwee-uhs-lee",
             definition: "Flatteringly",
             sentence: "He followed obsequiously."),
        Word(word: "Sagaciousness", pronunciation: "suh-GAY-shuhs-ness",
             definition: "Wisdom",
             sentence: "The elder’s sagaciousness guided the village."),
        Word(word: "Intransigently", pronunciation: "in-TRAN-si-juhnt-lee",
             definition: "Uncompromisingly",
             sentence: "The council acted intransigently."),
        Word(word: "Pulverizably", pronunciation: "PUHL-vuh-ry-zuh-blee",
             definition: "Able to be crushed",
             sentence: "The rocks were pulverizably crushed."),
        Word(word: "Luminously", pronunciation: "LOO-muh-nuhs-lee",
             definition: "Radiantly",
             sentence: "The candle shone luminously."),
        Word(word: "Redolently", pronunciation: "RED-uh-luhnt-lee",
             definition: "Fragrantly",
             sentence: "The kitchen smelled redolently."),
        Word(word: "Exigently", pronunciation: "EK-si-juhnt-lee",
             definition: "Urgently",
             sentence: "The matter had to be addressed exigently."),
        Word(word: "Vicissitudinously", pronunciation: "vi-SIS-i-TOO-di-nuhs-lee",
             definition: "With frequent changes",
             sentence: "Life changes vicissitudinously."),
        Word(word: "Evanescently", pronunciation: "EV-uh-NES-uhnt-lee",
             definition: "Briefly",
             sentence: "The rainbow appeared evanescently."),
        Word(word: "Ineffably", pronunciation: "in-EF-uh-blee",
             definition: "Indescribably",
             sentence: "The view was ineffably beautiful."),
        Word(word: "Sagaciously", pronunciation: "suh-GAY-shuhs-lee",
             definition: "Wisely",
             sentence: "He acted sagaciously."),
        Word(word: "Obstreperously", pronunciation: "ob-STREP-er-uhs-lee",
             definition: "Noisily",
             sentence: "The protesters acted obstreperously."),
    ]
}
