
import Foundation

extension Word {
    static let medium: [Word] = [
        Word(word: "Accurate", pronunciation: "AK-yuh-ruht",
             definition: "Correct and exact",
             sentence: "Her answer was accurate.",
             difficulty: .medium),
        Word(word: "Active", pronunciation: "AK-tiv",
             definition: "Engaged in action or activity",
             sentence: "He leads an active lifestyle.",
             difficulty: .medium),
        Word(word: "Adapt", pronunciation: "uh-DAPT",
             definition: "To adjust to new conditions",
             sentence: "Animals adapt to their environment.",
             difficulty: .medium),
        Word(word: "Alert", pronunciation: "uh-LURT",
             definition: "Watchful and ready",
             sentence: "Be alert when crossing the street.",
             difficulty: .medium),
        Word(word: "Ancient", pronunciation: "AYN-shuhnt",
             definition: "Very old or from the past",
             sentence: "The ancient ruins amazed the tourists.",
             difficulty: .medium),
        Word(word: "Angry", pronunciation: "ANG-gree",
             definition: "Feeling strong displeasure",
             sentence: "He was angry at the delay.",
             difficulty: .medium),
        Word(word: "Answer", pronunciation: "AN-sur",
             definition: "A response to a question",
             sentence: "She gave the correct answer.",
             difficulty: .medium),
        Word(word: "Brave", pronunciation: "brayv",
             definition: "Not afraid",
             sentence: "The soldier was brave.",
             difficulty: .medium),
        Word(word: "Bright", pronunciation: "BRYT",
             definition: "Full of light or intelligence",
             sentence: "The sun was bright today.",
             difficulty: .medium),
        Word(word: "Calm", pronunciation: "kahm",
             definition: "Peaceful, not angry",
             sentence: "Stay calm during the storm.",
             difficulty: .medium),
        Word(word: "Careful", pronunciation: "KAYR-fuhl",
             definition: "Cautious to avoid mistakes",
             sentence: "Be careful with glass objects.",
             difficulty: .medium),
        Word(word: "Careless", pronunciation: "KAYR-lis",
             definition: "Not paying attention",
             sentence: "He made a careless error.",
             difficulty: .medium),
        Word(word: "Change", pronunciation: "CHAYNJ",
             definition: "To make different",
             sentence: "Change can be challenging.",
             difficulty: .medium),
        Word(word: "Clear", pronunciation: "kleer",
             definition: "Easy to see or understand",
             sentence: "Her explanation was clear.",
             difficulty: .medium),
        Word(word: "Close", pronunciation: "klohs",
             definition: "Near in space or relationship",
             sentence: "They live close to the park.",
             difficulty: .medium),
        Word(word: "Common", pronunciation: "KOM-uhn",
             definition: "Ordinary or usual",
             sentence: "It’s common to feel nervous.",
             difficulty: .medium),
        Word(word: "Compete", pronunciation: "kuhm-PEET",
             definition: "To try to win",
             sentence: "Athletes compete in the games.",
             difficulty: .medium),
        Word(word: "Complete", pronunciation: "kuhm-PLEET",
             definition: "Having all parts",
             sentence: "He completed the puzzle.",
             difficulty: .medium),
        Word(word: "Confident", pronunciation: "KON-fi-duhnt",
             definition: "Sure of oneself",
             sentence: "She felt confident in her skills.",
             difficulty: .medium),
        Word(word: "Consider", pronunciation: "kuhn-SID-ur",
             definition: "To think carefully",
             sentence: "Consider all the options.",
             difficulty: .medium),
        Word(word: "Correct", pronunciation: "kuh-REKT",
             definition: "Free from errors",
             sentence: "Your answer is correct.",
             difficulty: .medium),
        Word(word: "Courage", pronunciation: "KUR-ij",
             definition: "The ability to face fear",
             sentence: "It takes courage to speak up.",
             difficulty: .medium),
        Word(word: "Create", pronunciation: "kree-AYT",
             definition: "To make something new",
             sentence: "She likes to create art.",
             difficulty: .medium),
        Word(word: "Curious", pronunciation: "KYOOR-ee-uhs",
             definition: "Wanting to know more",
             sentence: "He was curious about space.",
             difficulty: .medium),
        Word(word: "Danger", pronunciation: "DAYN-jur",
             definition: "The possibility of harm",
             sentence: "Beware of danger on the road.",
             difficulty: .medium),
        Word(word: "Decide", pronunciation: "di-SYD",
             definition: "To make a choice",
             sentence: "I need to decide quickly.",
             difficulty: .medium),
        Word(word: "Delight", pronunciation: "dih-LYT",
             definition: "Great pleasure",
             sentence: "The gift brought delight.",
             difficulty: .medium),
        Word(word: "Difficult", pronunciation: "DIF-i-kuhlt",
             definition: "Not easy to do",
             sentence: "The test was difficult.",
             difficulty: .medium),
        Word(word: "Direct", pronunciation: "di-REKT",
             definition: "Straightforward or clear",
             sentence: "Give me direct instructions.",
             difficulty: .medium),
        Word(word: "Discuss", pronunciation: "di-SKUS",
             definition: "To talk about something",
             sentence: "We will discuss the plan tomorrow.",
             difficulty: .medium),
        Word(word: "Divide", pronunciation: "di-VAHYD",
             definition: "To separate into parts",
             sentence: "Divide the cake evenly.",
             difficulty: .medium),
        Word(word: "Doubt", pronunciation: "dout",
             definition: "A feeling of uncertainty",
             sentence: "I have no doubt about her honesty.",
             difficulty: .medium),
        Word(word: "Effort", pronunciation: "EF-urt",
             definition: "Hard work",
             sentence: "She gave her best effort.",
             difficulty: .medium),
        Word(word: "Empty", pronunciation: "EMP-tee",
             definition: "Containing nothing",
             sentence: "The room was empty.",
             difficulty: .medium),
        Word(word: "Enough", pronunciation: "ee-NUHF",
             definition: "Sufficient",
             sentence: "There is enough food for everyone.",
             difficulty: .medium),
        Word(word: "Equal", pronunciation: "EE-kwuhl",
             definition: "The same in value",
             sentence: "All people are equal.",
             difficulty: .medium),
        Word(word: "Escape", pronunciation: "es-KAYP",
             definition: "To get away from danger",
             sentence: "They managed to escape the fire.",
             difficulty: .medium),
        Word(word: "Famous", pronunciation: "FAY-muhs",
             definition: "Well-known",
             sentence: "She became a famous singer.",
             difficulty: .medium),
        Word(word: "Fearful", pronunciation: "FEER-fuhl",
             definition: "Full of fear",
             sentence: "The child was fearful of the dark.",
             difficulty: .medium),
        Word(word: "Friendly", pronunciation: "FREND-lee",
             definition: "Kind and pleasant",
             sentence: "He has a friendly personality.",
             difficulty: .medium),
        Word(word: "Funny", pronunciation: "FUHN-ee",
             definition: "Causing laughter",
             sentence: "The comedian was very funny.",
             difficulty: .medium),
        Word(word: "Future", pronunciation: "FYOO-chur",
             definition: "Time yet to come",
             sentence: "Plan for the future carefully.",
             difficulty: .medium),
        Word(word: "Gentle", pronunciation: "JEN-tl",
             definition: "Kind and soft",
             sentence: "The dog is gentle.",
             difficulty: .medium),
        Word(word: "Glad", pronunciation: "glad",
             definition: "Feeling happy",
             sentence: "I’m glad you came.",
             difficulty: .medium),
        Word(word: "Great", pronunciation: "greyt",
             definition: "Very good or large",
             sentence: "She did a great job.",
             difficulty: .medium),
        Word(word: "Happy", pronunciation: "HAP-ee",
             definition: "Feeling pleasure or joy",
             sentence: "The children were happy.",
             difficulty: .medium),
        Word(word: "Healthy", pronunciation: "HEL-thee",
             definition: "Good for health",
             sentence: "Eating vegetables keeps you healthy.",
             difficulty: .medium),
        Word(word: "Helpful", pronunciation: "HELP-fuhl",
             definition: "Providing assistance",
             sentence: "He is always helpful.",
             difficulty: .medium),
        Word(word: "Honest", pronunciation: "AH-nist",
             definition: "Truthful and fair",
             sentence: "Be honest with your friends.",
             difficulty: .medium),
        Word(word: "Important", pronunciation: "im-PAWR-tuhnt",
             definition: "Significant, necessary",
             sentence: "It’s important to study.",
             difficulty: .medium),
        Word(word: "Impossible", pronunciation: "im-PAH-suh-buhl",
             definition: "Cannot be done",
             sentence: "It seemed impossible to climb the mountain.",
             difficulty: .medium),
        Word(word: "Improve", pronunciation: "im-PROOV",
             definition: "To make better",
             sentence: "Practice will improve your skills.",
             difficulty: .medium),
        Word(word: "Include", pronunciation: "in-KLOOD",
             definition: "To contain as part of something",
             sentence: "Please include your name on the form.",
             difficulty: .medium),
        Word(word: "Increase", pronunciation: "in-KREES",
             definition: "To become greater",
             sentence: "They plan to increase production.",
             difficulty: .medium),
        Word(word: "Independent", pronunciation: "in-di-PEN-dent",
             definition: "Free from control",
             sentence: "She is independent and self-reliant.",
             difficulty: .medium),
        Word(word: "Inform", pronunciation: "in-FORM",
             definition: "To give knowledge",
             sentence: "Please inform me of any changes.",
             difficulty: .medium),
        Word(word: "Interesting", pronunciation: "IN-tuh-res-ting",
             definition: "Attracting attention",
             sentence: "The story was interesting.",
             difficulty: .medium),
        Word(word: "Invite", pronunciation: "in-VYT",
             definition: "To ask someone to come",
             sentence: "I will invite my friends to the party.",
             difficulty: .medium),
        Word(word: "Journey", pronunciation: "JUR-nee",
             definition: "A trip from one place to another",
             sentence: "Their journey lasted three days.",
             difficulty: .medium),
        Word(word: "Kind", pronunciation: "kahynd",
             definition: "Being friendly and generous",
             sentence: "He is kind to animals.",
             difficulty: .medium),
        Word(word: "Knowledge", pronunciation: "NAWL-ij",
             definition: "Information or understanding",
             sentence: "Knowledge is power.",
             difficulty: .medium),
        Word(word: "Laugh", pronunciation: "laf",
             definition: "To make sounds expressing happiness",
             sentence: "They laugh at the joke.",
             difficulty: .medium),
        Word(word: "Learn", pronunciation: "lur-n",
             definition: "To gain knowledge",
             sentence: "Children learn quickly.",
             difficulty: .medium),
        Word(word: "Listen", pronunciation: "LIS-uhn",
             definition: "To hear attentively",
             sentence: "Listen carefully to the teacher.",
             difficulty: .medium),
        Word(word: "Lonely", pronunciation: "LOHN-lee",
             definition: "Feeling alone",
             sentence: "He felt lonely in the city.",
             difficulty: .medium),
        Word(word: "Lucky", pronunciation: "LUHK-ee",
             definition: "Having good fortune",
             sentence: "She was lucky to find the keys.",
             difficulty: .medium),
        Word(word: "Modern", pronunciation: "MAH-dern",
             definition: "Relating to the present time",
             sentence: "The building has a modern design.",
             difficulty: .medium),
        Word(word: "Natural", pronunciation: "NACH-uh-ruhl",
             definition: "Existing in nature",
             sentence: "Natural beauty is everywhere.",
             difficulty: .medium),
        Word(word: "Necessary", pronunciation: "NEH-suh-ser-ee",
             definition: "Required, essential",
             sentence: "Water is necessary for life.",
             difficulty: .medium),
        Word(word: "Neighbor", pronunciation: "NEY-bur",
             definition: "A person living nearby",
             sentence: "My neighbor helped me.",
             difficulty: .medium),
        Word(word: "Nervous", pronunciation: "NUR-vuhs",
             definition: "Feeling anxious",
             sentence: "He was nervous about the test.",
             difficulty: .medium),
        Word(word: "Notice", pronunciation: "NO-tis",
             definition: "To observe or pay attention",
             sentence: "I didn’t notice the sign.",
             difficulty: .medium),
        Word(word: "Number", pronunciation: "NUHM-bur",
             definition: "A symbol representing quantity",
             sentence: "Write your phone number here.",
             difficulty: .medium),
        Word(word: "Offer", pronunciation: "AW-fur",
             definition: "To present or propose",
             sentence: "They offer a free trial.",
             difficulty: .medium),
        Word(word: "Open", pronunciation: "OH-puhn",
             definition: "Not closed",
             sentence: "Leave the door open.",
             difficulty: .medium),
        Word(word: "Order", pronunciation: "OR-dur",
             definition: "A request or arrangement",
             sentence: "Place your order online.",
             difficulty: .medium),
        Word(word: "Organize", pronunciation: "OR-guh-nyz",
             definition: "To arrange systematically",
             sentence: "Organize your desk.",
             difficulty: .medium),
        Word(word: "Patient", pronunciation: "PAY-shuhnt",
             definition: "Able to wait calmly",
             sentence: "Be patient with children.",
             difficulty: .medium),
        Word(word: "Peaceful", pronunciation: "PEES-fuhl",
             definition: "Free from disturbance",
             sentence: "The garden is peaceful.",
             difficulty: .medium),
        Word(word: "Perfect", pronunciation: "PUR-fekt",
             definition: "Without mistakes",
             sentence: "The painting is perfect.",
             difficulty: .medium),
        Word(word: "Pleasant", pronunciation: "PLEZ-uhnt",
             definition: "Giving pleasure",
             sentence: "It was a pleasant evening.",
             difficulty: .medium),
        Word(word: "Polite", pronunciation: "puh-LYT",
             definition: "Showing good manners",
             sentence: "Be polite to your teachers.",
             difficulty: .medium),
        Word(word: "Popular", pronunciation: "PAH-pyuh-lur",
             definition: "Liked by many people",
             sentence: "Soccer is popular worldwide.",
             difficulty: .medium),
        Word(word: "Powerful", pronunciation: "POW-ur-fuhl",
             definition: "Having great strength",
             sentence: "The engine is powerful.",
             difficulty: .medium),
        Word(word: "Prepare", pronunciation: "pri-PAIR",
             definition: "To make ready",
             sentence: "Prepare your homework.",
             difficulty: .medium),
        Word(word: "Present", pronunciation: "PREZ-uhnt",
             definition: "Being in a place",
             sentence: "He was present at the meeting.",
             difficulty: .medium),
        Word(word: "Pretty", pronunciation: "PRIH-tee",
             definition: "Attractive",
             sentence: "The flowers are pretty.",
             difficulty: .medium),
        Word(word: "Private", pronunciation: "PRY-vuht",
             definition: "For individual use",
             sentence: "Keep the information private.",
             difficulty: .medium),
        Word(word: "Protect", pronunciation: "pruh-TEKT",
             definition: "To keep safe",
             sentence: "Wear a helmet to protect your head.",
             difficulty: .medium),
        Word(word: "Proud", pronunciation: "proud",
             definition: "Feeling pleased about achievements",
             sentence: "She is proud of her work.",
             difficulty: .medium),
        Word(word: "Quick", pronunciation: "kwik",
             definition: "Fast",
             sentence: "He is quick to respond.",
             difficulty: .medium),
        Word(word: "Quiet", pronunciation: "KWY-uht",
             definition: "Making little or no noise",
             sentence: "The library was quiet.",
             difficulty: .medium),
        Word(word: "Read", pronunciation: "reed",
             definition: "To look at and understand words",
             sentence: "I like to read books.",
             difficulty: .medium),
        Word(word: "Ready", pronunciation: "RED-ee",
             definition: "Prepared",
             sentence: "She is ready for the exam.",
             difficulty: .medium),
        Word(word: "Real", pronunciation: "reel",
             definition: "True or actual",
             sentence: "This is a real diamond.",
             difficulty: .medium),
        Word(word: "Relax", pronunciation: "ri-LAKS",
             definition: "To rest or loosen up",
             sentence: "Relax after a long day.",
             difficulty: .medium),
        Word(word: "Respect", pronunciation: "ri-SPEKT",
             definition: "Admiration for someone",
             sentence: "Show respect to elders.",
             difficulty: .medium),
        Word(word: "Safe", pronunciation: "sayf",
             definition: "Not in danger",
             sentence: "The children are safe.",
             difficulty: .medium),
        Word(word: "Satisfied", pronunciation: "SAT-is-fyd",
             definition: "Contented",
             sentence: "He felt satisfied with the result.",
             difficulty: .medium),
        Word(word: "Secure", pronunciation: "si-KYOOR",
             definition: "Protected from harm",
             sentence: "Keep your valuables secure.",
             difficulty: .medium),
        Word(word: "Sensitive", pronunciation: "SEN-suh-tiv",
             definition: "Easily affected",
             sentence: "Be sensitive to others' feelings.",
             difficulty: .medium),
        Word(word: "Simple", pronunciation: "SIM-puhl",
             definition: "Easy to understand or do",
             sentence: "The instructions are simple.",
             difficulty: .medium),
        Word(word: "Smart", pronunciation: "smart",
             definition: "Intelligent or clever",
             sentence: "She is very smart.",
             difficulty: .medium),
        Word(word: "Smooth", pronunciation: "smoohth",
             definition: "Even and without roughness",
             sentence: "The table surface is smooth.",
             difficulty: .medium),
        Word(word: "Soft", pronunciation: "sof",
             definition: "Not hard or rough",
             sentence: "The pillow is soft.",
             difficulty: .medium),
        Word(word: "Strong", pronunciation: "strong",
             definition: "Having great power or strength",
             sentence: "He is strong enough to lift it.",
             difficulty: .medium),
        Word(word: "Successful", pronunciation: "suhk-SESS-fuhl",
             definition: "Achieving desired results",
             sentence: "She is successful in her career.",
             difficulty: .medium),
        Word(word: "Talented", pronunciation: "TAL-uhn-tid",
             definition: "Having a natural skill",
             sentence: "He is a talented musician.",
             difficulty: .medium),
        Word(word: "Thankful", pronunciation: "THANGK-fuhl",
             definition: "Feeling grateful",
             sentence: "She is thankful for her family.",
             difficulty: .medium),
        Word(word: "Thoughtful", pronunciation: "THAWT-fuhl",
             definition: "Considerate of others",
             sentence: "He is always thoughtful.",
             difficulty: .medium),
        Word(word: "Tidy", pronunciation: "TY-dee",
             definition: "Neat and organized",
             sentence: "Keep your room tidy.",
             difficulty: .medium),
        Word(word: "Tough", pronunciation: "tuhf",
             definition: "Strong and resilient",
             sentence: "She is tough and persistent.",
             difficulty: .medium),
        Word(word: "Trust", pronunciation: "truhst",
             definition: "Belief in reliability",
             sentence: "I trust my friends.",
             difficulty: .medium),
        Word(word: "Useful", pronunciation: "YOOS-fuhl",
             definition: "Helping to do something",
             sentence: "This tool is very useful.",
             difficulty: .medium),
        Word(word: "Valuable", pronunciation: "VAL-yoo-uh-buhl",
             definition: "Worth a lot",
             sentence: "Gold is valuable.",
             difficulty: .medium),
        Word(word: "Warm", pronunciation: "wawrm",
             definition: "Having or giving heat",
             sentence: "The sun feels warm.",
             difficulty: .medium),
        Word(word: "Weak", pronunciation: "week",
             definition: "Not strong",
             sentence: "He felt weak after illness.",
             difficulty: .medium),
        Word(word: "Wise", pronunciation: "wyz",
             definition: "Having good judgment",
             sentence: "The wise man gave advice.",
             difficulty: .medium),
        Word(word: "Wonderful", pronunciation: "WUHN-der-fuhl",
             definition: "Very good or delightful",
             sentence: "It was a wonderful experience.",
             difficulty: .medium),
        Word(word: "Worthy", pronunciation: "WUR-thee",
             definition: "Deserving respect or attention",
             sentence: "She is worthy of the award.",
             difficulty: .medium),
        Word(word: "Young", pronunciation: "yuhng",
             definition: "Not old",
             sentence: "The young boy smiled.",
             difficulty: .medium),
        Word(word: "Youthful", pronunciation: "YOOTH-fuhl",
             definition: "Having qualities of youth",
             sentence: "She looks youthful.",
             difficulty: .medium),
        Word(word: "Zealous", pronunciation: "ZEL-uhs",
             definition: "Full of passion",
             sentence: "He is zealous about his work.",
             difficulty: .medium)
    ]
}
